export declare const purge: string[];
export declare namespace theme {
  export namespace fontFamily {
    export const heading: string[];
    export const body: string[];
  }
  export namespace extend {
    export const colors: {
      "primary-100": string;
      "primary-200": string;
      "primary-300": string;
      "primary-400": string;
      "primary-500": string;
      "primary-600": string;
      "primary-700": string;
      "primary-800": string;
      "primary-900": string;
      "primary-transparent-100": string;
      "primary-transparent-200": string;
      "primary-transparent-300": string;
      "primary-transparent-400": string;
      "primary-transparent-500": string;
      "primary-transparent-600": string;
      "success-100": string;
      "success-200": string;
      "success-300": string;
      "success-400": string;
      "success-500": string;
      "success-600": string;
      "success-700": string;
      "success-800": string;
      "success-900": string;
      "success-transparent-100": string;
      "success-transparent-200": string;
      "success-transparent-300": string;
      "success-transparent-400": string;
      "success-transparent-500": string;
      "success-transparent-600": string;
      "info-100": string;
      "info-200": string;
      "info-300": string;
      "info-400": string;
      "info-500": string;
      "info-600": string;
      "info-700": string;
      "info-800": string;
      "info-900": string;
      "info-transparent-100": string;
      "info-transparent-200": string;
      "info-transparent-300": string;
      "info-transparent-400": string;
      "info-transparent-500": string;
      "info-transparent-600": string;
      "warning-100": string;
      "warning-200": string;
      "warning-300": string;
      "warning-400": string;
      "warning-500": string;
      "warning-600": string;
      "warning-700": string;
      "warning-800": string;
      "warning-900": string;
      "warning-transparent-100": string;
      "warning-transparent-200": string;
      "warning-transparent-300": string;
      "warning-transparent-400": string;
      "warning-transparent-500": string;
      "warning-transparent-600": string;
      "danger-100": string;
      "danger-200": string;
      "danger-300": string;
      "danger-400": string;
      "danger-500": string;
      "danger-600": string;
      "danger-700": string;
      "danger-800": string;
      "danger-900": string;
      "danger-transparent-100": string;
      "danger-transparent-200": string;
      "danger-transparent-300": string;
      "danger-transparent-400": string;
      "danger-transparent-500": string;
      "danger-transparent-600": string;
      "basic-300": string;
      "basic-500": string;
      "basic-600": string;
      "secondary-100": string;
      "secondary-300": string;
      "secondary-500": string;
      "secondary-700": string;
      "coral-100": string;
      "coral-300": string;
      "coral-500": string;
      "coral-700": string;
      "background-primary": string;
      "background-alternative": string;
    };
  }
}
